#! /bin/sh
source /home/zaytos/Programacion/scripts/hz_conf &
pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V 

bspc config border_width         2
bspc config window_gap           6

bspc config normal_border_color "#54587b"
bspc config presel_feedback_color "#009a8b"
bspc config focused_border_color "#009a8b"

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# background image
feh --bg-fill /home/zaytos/Imagenes/hacker_cyberpunk0.png &

# polybar
#~/.config/polybar/neon/launch.sh

# picom
picom &
